

export const cartProducts = []

export const paymentUrl = {
    1: "/mercadopago",
    2: "/rating",
    3: "/rating"
  }



export const idiomas = [
  { lang: "es", message: "Bienvenido", name: "español" },
  { lang: "en", message: "Welcome", name: "english" },
  { lang: "pt", message: "Bem-vindo", name: "português" },
  { lang: "fr", message: "Bienvenue", name: "français" },
  { lang: "it", message: "Benvenuto", name: "italiano" },
];

export const terms_es = "Estos términos y condiciones de uso (en adelante, 'Términos y Condiciones') regulan el uso de la aplicación web iMenu (en adelante, la 'Aplicación') y los servicios ofrecidos por Polipus Team (en adelante, la 'Empresa'). Al acceder y utilizar la Aplicación, usted acepta y se compromete a cumplir con estos Términos y Condiciones. Si no está de acuerdo con estos Términos y Condiciones, por favor, absténgase de utilizar la Aplicación. \n1. Registro de Usuarios \n1.1. Para utilizar ciertas funcionalidades de la Aplicación, usted puede optar por registrarse como usuario. Al registrarse, usted acepta proporcionar información precisa y actualizada, incluyendo su nombre, dirección de correo electrónico, dirección, número de teléfono, ciudad, fecha de nacimiento y otros datos personales que puedan ser solicitados.\n1.2. Usted es responsable de mantener la confidencialidad de su información de inicio de sesión y contraseña. Cualquier actividad realizada en su cuenta será de su responsabilidad.\n2. Uso de la Aplicación \n2.1. La Aplicación permite a los usuarios seleccionar productos y menús de comercios locales, agregar productos a un carrito de compras y realizar pagos, ya sea en efectivo o con tarjeta de crédito. \n2.2. Usted acepta que es responsable de revisar y confirmar su pedido antes de realizar el pago. La Empresa no se hace responsable de errores en los pedidos realizados por los usuarios. \n2.3. Usted se compromete a utilizar la Aplicación de manera responsable y a cumplir con todas las leyes y regulaciones aplicables. \n3. Privacidad y Protección de Datos Personales \n3.1. La Empresa recopila y almacena los datos personales proporcionados por los usuarios de acuerdo con su Política de Privacidad. Al utilizar la Aplicación, usted acepta la recopilación, uso y almacenamiento de sus datos personales de acuerdo con esta política. \n4. Pagos \n4.1. Los pagos realizados a través de la Aplicación se procesarán de manera segura. Usted acepta que la Empresa puede retener cierta información de pago de acuerdo con su Política de Privacidad.\n5. Cancelación y Devoluciones\n5.1. Las políticas de cancelación y devoluciones de pedidos pueden variar según el comercio. Usted acepta revisar y cumplir con las políticas de cancelación y devoluciones de cada comercio antes de realizar un pedido.\n6. Modificaciones y Terminación. \n6.1. La Empresa se reserva el derecho de modificar o terminar la Aplicación o estos Términos y Condiciones en cualquier momento, a su entera discreción. \n7. Ley Aplicable y Jurisdicción \n7.1. Estos Términos y Condiciones se rigen por las leyes vigentes en Argentina. Cualquier disputa que surja en relación con estos Términos y Condiciones estará sujeta a la \njurisdicción exclusiva de los tribunales de Buenos Aires, Argentina.\n8. Contacto \n8.1. Si tiene alguna pregunta o inquietud sobre estos Términos y Condiciones, por favor, póngase en contacto con nosotros a través de polipus2023@gmail.com.";

export const terms_en = "These terms and conditions of use (hereinafter, the 'Terms and Conditions') govern the use of the iMenu web application (hereinafter, the 'Application') and the services offered by Polipus Team (hereinafter, the 'Company'). \nBy accessing and using the Application, you agree to and undertake to comply with these Terms and Conditions. If you do not agree with these Terms and Conditions, please refrain from using the Application. \n1. User Registration \n1.1. In order to use certain features of the Application, you may opt to register as a user. By registering, you agree to provide accurate and up-to-date information, including your name, email address, address, phone number, city, date of birth, and other personal information that may be requested. \n1.2. You are responsible forining the confidentiality of your login information and password. Any activity performed on your account will be your responsibility. \n2. Use of the Application \n2.1. The App allows users to select products and menus from local stores, add products to a shopping cart and make payments, whether in cash or with credit card. \n2.2. You agree that you are responsible for reviewing and confirming your order before making the payment. The Company is not responsible for errors in orders made by users. \n2.3. You agree to use the Application responsibly and to comply with all applicable laws and regulations. \nPrivacy and Personal Data Protection \n3.1. The Company collects and stores personal data provided by users in accordance with its Privacy Policy. By using the Application, you agree to the collection, use and storage of your personal data in accordance with this policy. \n4. Payments \n4.1. Payments made through the App will be processed securely. You agree that the Company may retain certain payment information in accordance with its Privacy Policy. \n5. Cancellation and Returns \n5.1. Cancellation and return policies may vary by trade. You agree to review and comply with the cancellation and refund policies of each trade before placing an order.\n6. Modifications and Termination. \n6.1. The Company reserves the right to modify or terminate the Application or these Terms and Conditions at any time, at its sole discretion. \n7. Applicable Law and Jurisdiction \n7.1. These Terms and Conditions are governed by the laws in force in Argentina. Any dispute arising from these Terms and Conditions will be subject to the exclusive jurisdiction of the courts of Buenos Aires, Argentina. \n8. Contact \n8.1. If you have any questions or concerns about these Terms and Conditions, please contact us at polipus2023@gmail.com.";

export const terms_port = "Estes termos e condições de uso (doravante, os “Termos e Condições”) regem a utilização da aplicação web iMenu (de agora em diante, a “Aplicação”) e dos serviços oferecidos pela Polipus Team (de hoje em diante a “Empresa”). Ao acessar e usar o Aplicativo, você aceita e concorda em cumprir estes Termos e Condições. Se você não concorda com estes Termos e Condições, por favor, abstenha-se de usar o Aplicativo. \n.1 Registro de Usuários \n.1.1 Para utilizar certas funcionalidades da Aplicação, você pode optar por se registrar como usuário. Ao se registrar, você concorda em fornecer informações precisas e atualizadas, incluindo seu nome, endereço de e-mail, morada, número de telefone, cidade, data de nascimento e outros dados pessoais que possam ser solicitados.\n1.2.Você é responsável por manter a confidencialidade de suas informações de login e senha. Qualquer atividade realizada na sua conta será da sua responsabilidade.A aplicação permite aos usuários selecionar produtos e menus de lojas locais, adicionar produtos a um carrinho de compras e efetuar pagamentos, seja em dinheiro ou com cartão de crédito. Você concorda que é responsável por rever e confirmar seu pedido antes de efetuar o pagamento. A Empresa não se responsabiliza por erros nos pedidos feitos pelos usuários. Você concorda em usar o Aplicativo de forma responsável e em cumprir todas as leis e regulamentos aplicáveis. \n3. privacidade e proteção de dados pessoais \n3.1.A Empresa recolhe e armazena os dados pessoais fornecidos pelos usuários de acordo com sua Política de Privacidade. Ao usar o Aplicativo, você concorda com a coleta, uso e armazenamento de seus dados pessoais de acordo com esta política. Pagamentos \n4.1.Os pagamentos feitos através da Aplicação serão processados de forma segura. Você concorda que a Empresa pode reter certas informações de pagamento de acordo com sua Política de Privacidade.\n5.Cancelamento e Devoluções\n5.1.As políticas de cancelamento e devolução de pedidos podem variar de acordo com o comércio. Você concorda em revisar e cumprir as políticas de cancelamento e devolução de cada comércio antes de fazer um pedido.\n6. Modificações e Terminação. A Empresa reserva-se o direito de modificar ou encerrar o Aplicativo ou estes Termos e Condições a qualquer momento, a seu exclusivo critério. Lei Aplicável e Jurisdição \n7.1.Esses Termos e Condições são regidos pelas leis vigentes na Argentina. Qualquer disputa que surja em relação a estes Termos e Condições estará sujeita à jurisdição exclusiva dos tribunais de Buenos Aires, Argentina.Se você tiver alguma dúvida ou preocupação sobre estes Termos e Condições, entre em contato conosco através de polipus2023@gmail.com."
