export let all_app_texts = [
  { QrScanner_title: "Escanea un código Qr" },
  { loader_wait: "Espera mientras preparamos el menu" },
  { languages_termsConditions: "Acepto los términos y condiciones de uso" },
  { languages_seeConditions: "Ver condiciones aqui" },
  { languages_termsConditions: "Términos y condiciones" },
  { languages_acceptConditions: "Acepto los términos y condiciones de uso" },
  { languages_acceptButton: "Aceptar" },
  { languages_cancelButton: "Cancelar" },
  { loader_title: "Espera mientras preparamos el menu" },
  { language_button: "Comenzar" },
  { login_firstStep: "Da el primer paso" },
  { login_access: "accede utilizando tu correo de Google" },
  { login_googleButton: "Accede con Google" },
  { login_noGoogleButton: "Acceder sin registro" },
  { login_slogan: "La velocidad es" },
  { login_sloganBig: "nuestro plato fuerte" },
  { navBar_disconnect: "Desconectar" },
  { welcome_title: "¡Bienvenido!" },
  { welcome_subtitle: "Estas por pedir en: " },
  { welcome_sector: "Sector " },
  { welcome_table: "Mesa " },
  { welcome_poweredby: "impulsado por" },
  { welcome_order: "Hacer pedido" },
  { welcome_viewproducts: "Ver productos" },
  { welcome_instructions: "Instrucciones" },
  { closed_isClosed: "Se encuentra cerrado" },
  { closed_comeBack: "¡Vuelve pronto!" },
  { closed_needHelp: "¿Necesitas ayuda?" },
  { contactFooter_contact: "Contáctanos" },
  { contactFooter_iMenu: "Quiero iMenu" },
  { instructions_title: "Instrucciones" },
  { instructions_subtitle: "¿Como hacer tu pedido en i menu?" },
  {
    instructions_instruction_1:
      "Selecciona productos del menú, presiona la tarjeta del producto",
  },
  {
    instructions_instruction_2:
      "Una vez seleccionados tus productos, presiona en 'ver producto' para confirmar tu pedido",
  },
  {
    instructions_instruction_3:
      "Realiza el pago de tu pedido en efectivo o a través de Mercadopago",
  },
  { instructions_instruction_4: "¡Tu pedido estará en camino!" },
  { instructions_poweredby: "impulsado por " },
  { instructions_order: "Hacer pedido" },
  { loginModal_title: "Ingresa con google, para una mejor experiencia!" },
  { loginModal_googleButton: "Accede con Google" },
  { loginModal_omitButton: "Omitir" },
  { banner_table: "Mesa " },
  { searchbar_placeholder: "¿Que quieres pedir?" },
  { categories_title: "Categorias" },
  { productModal_commentLabel: "Comentarios" },
  { productModal_commentPlaceholder: "Agrega comentarios y observaciones" },
  { productModal_addButton: "Agregar" },
  { footer_yourOrder: "Tu pedido" },
  { footer_products: "Productos" },
  { footer_total: "Total" },
  { footer_payButton: "Pagar" },
  { footer_viewproducts: "Ver productos" },
  { payment_title: "Pagar" },
  { payment_managePayment: "Gestione su pago desde aqui" },
  { payment_cash: "Efectivo" },
  { payment_poweredby: "impulsado por" },
  { payment_continue: "Continuar" },
  { orderInfo_table: "Mesa" },
  { orderInfo_paymentTotal: "Total a pagar:" },
  { mercadoPago_payButton: "Pagar" },
  { rating_preparingOrder: "está preparando tu pedido" },
  { rating_reviewQuestion: "¿Como te fue con la app?" },
  { rating_thanks: "¡Gracias!" },
  { rating_yourOpinion: "Tu opinion nos ayuda a crecer" },
  { rating_reviewLabel: "Danos tu opinión" },
  { rating_reviewPlaceholder: "¿Te gusta nuestra forma de hacer las cosas?" },
  { rating_send: "Enviar" },
  { rating_backButton: "Volver a pedir" },
];
